@startuml
'https://plantuml.com/sequence-diagram


class ToDoLists
{
    main()
    start()
}

class ToDoListController
{
    addListClicked()
    removeListClicked()
    editListTitleClicked()
    addToListClicked()
    removeFromListClicked()
    editDescOfItemClicked()
    editDateOfItemClicked()
    markCompleteClicked()
    allListsClicked()
    incompleteListClicked()
    completeListClicked()
    exportListClicked()
    exportSingleListClicked()
    exportAllListClicked()
    importListClicked()
    importSingleListClicked()
    importSeveralListClicked()
}

class itemFormat
{
    name
    desc
    completed
    -index
}

javafx.Application <|-- ToDoLists
ToDoLists - ToDoListController
ToDoLists - itemFormat

@enduml